[package]
name = "storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
name = "storage"
path = "src/lib.rs"

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
common = { version = "0.1.0", path = "../common" }
duckdb = { workspace = true, features = ["chrono", "uuid", "serde_json", "json"] }
hex.workspace = true
parking_lot = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2.workspace = true
statuscore = { path = "../core" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[lints]
workspace = true
