name: CI

on:
  push:
    branches: ["main", "master"]
    tags: ["v*"]
  pull_request:
    branches: ["main", "master"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_BUILD_RUSTC_WRAPPER: ""

jobs:
  ci:
    name: Lint Test Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: taiki-e/install-action@v2
        with:
          tool: just,cargo-machete,typos-cli,rumdl,leptosfmt

      - name: Install cargo-sort
        run: cargo install cargo-sort

      - name: CI
        run: just ci
